// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwK5XwrxU3WCgwjGaCjj38z5ZJ4WvKJ80',
    appId: '1:112598131818:web:cdeec67ec51f0f83855613',
    messagingSenderId: '112598131818',
    projectId: 'todo-app-fa213',
    authDomain: 'todo-app-fa213.firebaseapp.com',
    storageBucket: 'todo-app-fa213.appspot.com',
    measurementId: 'G-6DSG9534N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBekyBrx55lJQ4D03UOqN28be1TGGTUM0',
    appId: '1:112598131818:android:0a3017893e1f346a855613',
    messagingSenderId: '112598131818',
    projectId: 'todo-app-fa213',
    storageBucket: 'todo-app-fa213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TlhsefQ1ig8bV6pgJgdO5CnvivnBV4Q',
    appId: '1:112598131818:ios:5c899884d34b07fc855613',
    messagingSenderId: '112598131818',
    projectId: 'todo-app-fa213',
    storageBucket: 'todo-app-fa213.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_TlhsefQ1ig8bV6pgJgdO5CnvivnBV4Q',
    appId: '1:112598131818:ios:5c899884d34b07fc855613',
    messagingSenderId: '112598131818',
    projectId: 'todo-app-fa213',
    storageBucket: 'todo-app-fa213.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwK5XwrxU3WCgwjGaCjj38z5ZJ4WvKJ80',
    appId: '1:112598131818:web:521e057251e94408855613',
    messagingSenderId: '112598131818',
    projectId: 'todo-app-fa213',
    authDomain: 'todo-app-fa213.firebaseapp.com',
    storageBucket: 'todo-app-fa213.appspot.com',
    measurementId: 'G-R4Q44VQJV0',
  );
}
